name: Build and push docker image to Amazon ECR

on:
  push:
    branches: ['main']
    paths: ['apps/**']

jobs:
  build-and-push-docker-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: 'us-east-2'
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY_NAME }}
        run: |
          TAG_LATEST=$REGISTRY/$REPOSITORY:latest
          docker build -t $TAG_LATEST .
          docker push $TAG_LATEST
      - name: Cleanup working dir
        run: rm -rf *
